# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: TypeSig
author: TypeSig Committee
email: committee@typesig.pl
description: >- # this means to ignore newlines until "baseurl:"
  Official website for TypeSig, a student-run special interest group for
  semantics, programming language theory, type theory, compilers, concurrency,
  and any other field of theoretical CS!
logo: assets/images/logo.svg
logo-wide: assets/images/logo-wide.svg
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://typesig.pl" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
highlighter: rouge
markdown: kramdown
  syntax_highlighter: rouge
#theme: minima
remote_theme: wowthemesnet/affiliates-jekyll-theme
sass:
  sass_dir: _sass
  style: :compressed
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-archives

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

paginate: 30
feed_items: 10
feed_update_period: daily


authors:
  jacob:
    name: Jacob Walters
    display_name: Jacob Walters
    avatar: 'assets/images/authors/jacob.jpg'
    web: https://jacobwalte.rs
    description: "World's biggest bike-shedding fan"

social:
  discord: https://discord.gg/dnXzHRkJww
  instagram: https://www.instagram.com/typesig/
